#!/bin/bash

set -exu

if [[ -z ${BOSH_ENVIRONMENT:-} ]]; then
  source cf-deployment-concourse-tasks/shared-functions
  setup_bosh_env_vars
fi

: ${BOSH_ENVIRONMENT:?must provide BOSH_* environment variables or BBL_STATE_DIR}

pushd release-tarball
  bosh upload-release $(find -maxdepth 1 -name "${RELEASE_TARBALL_GLOB}")
popd
