#!/bin/bash

set -exu

if [[ -z ${BOSH_ENVIRONMENT:-} ]]; then
  source cf-deployment-concourse-tasks/shared-functions
  setup_bosh_env_vars
fi

: ${BOSH_ENVIRONMENT:?must provide BOSH_* environment variables or BBL_STATE_DIR}

pushd release-tarball
  file="$(find -maxdepth 1 -name \"${RELEASE_TARBALL_GLOB}\")""
  if [[ -z ${file} ]]; then
    echo Unable to find tarball in ${PWD} with glob ${RELEASE_TARBALL_GLOB}
    exit 1
  fi

  bosh upload-release $(find -maxdepth 1 -name "${RELEASE_TARBALL_GLOB}")
popd
