platform: linux

inputs:
- name: metric-store-ci
- name: bbl-state
  optional: true
- name: release-tarball

params:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:


run:
  path: metric-store-ci/tasks/upload-release-tarball/task
