#!/bin/bash

set -exu

. ./log-cache-ci/tasks/shared_bash

calculate_version bosh-dev-release-dir/version bosh-dev-release-version bosh-new-dev-release-version "dev"
dev_version=$(cat bosh-new-dev-release-version/version | sed -r 's/-/+/')

pushd bosh-dev-release-dir
  if [[ -n ${JSON_KEY:-} ]]; then
    cat << EOF > config/private.yml
---
blobstore:
  options:
    credentials_source: static
    json_key: |
      $(echo ${JSON_KEY})
EOF
  fi

  # put go source files in src directory so go build is pleased.
  mkdir -p src/github.com/cloudfoundry/metric-store-release/src/{pkg,cmd}
  cp -r vendor/* src/
  cp -r src/pkg src/github.com/cloudfoundry/metric-store-release/src
  cp -r src/cmd src/github.com/cloudfoundry/metric-store-release/src

  bosh vendor-package golang-1.12-linux ../golang-release

  bosh create-release --force \
    --tarball ../oss-metric-store-dev-release/release-${dev_version}.tgz \
    --version "${dev_version}"
popd
