#!/bin/bash -eu
echo "running tile install"

. ./log-cache-ci/tasks/shared_bash

export RELEASE_VERSION=$(cat tile-version/version)

TILE_FILE=$(echo "$(set -- baked-tile/*.pivotal; echo "$1")")

source environment/environment.sh
source deployment-tools/prelude.sh
source deployment-tools/omg.sh

stemcell_filename=$(download-product ${STEMCELL_URL})

omg upload-product --product ${TILE_FILE}
omg stage-product --product-name "p-metric-store" --product-version ${RELEASE_VERSION}
omg configure-product --config ${PRODUCT_CONFIG_PATH}
omg upload-stemcell --stemcell ${stemcell_filename} --floating true --shasum ${STEMCELL_SHA}
omg apply-changes --product-name "p-metric-store"
