#!/usr/bin/env ruby
#
def header(txt)
  puts "\e[32m### #{txt}\e[0m"
end

def download_blob(filename)
  `wget "https://redirector.gvt1.com/edgedl/go/#{filename}" -O "golang-blobs/#{filename}"`
  check_process($?, "downloading #{filename}")
end

def check_process(process, action)
  if !process.success?
    raise "Command execution failed for #{action}"
  end
end

def to_version
  @to_version ||= ENV.fetch("VERSION")
end

def linux_filename(version)
  @linux_filename ||= "go#{version}.linux-amd64.tar.gz"
end

header "Downloading Linux blob..."
download_blob(linux_filename(to_version))
