platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/metric-store-tile

inputs:
  - name: final-tile
  - name: metric-store-pivnet-metadata
  - name: metric-store-osl

outputs:
  - name: final-tile

run:
  path: metric-store-ci/tasks/add-osl/task
