platform: linux

inputs:
  - name: final-tile
  - name: metric-store-pivnet-metadata
  - name: metric-store-osl
  - name: metric-store-ci

outputs:
  - name: final-tile

run:
  path: metric-store-ci/tasks/add-osl/task
