name: metric-store-grafana
features:
  converge_variables: true
instance_groups:
- name: grafana
  networks:
  - name: pws-cf
  stemcell: default
  vm_type: minimal
  persistent_disk_type: 1GB
  azs:
  - z2
  instances: 1
  jobs:
  - name: grafana
    release: prometheus
    properties:
      grafana:
        security:
          admin_password: ((grafana-admin-password))
          admin_username: admin
        server:
          root_url: https://grafana.observe.run.pivotal.io
          ssl_cert: ((grafana_ssl.certificate))
          ssl_key: ((grafana_ssl.private_key))
          protocol: https
        users:
          auto_assign_org_role: Editor
        auth:
          generic_oauth:
            name: UAA
            enabled: true
            allow_sign_up: true
            client_id: ((uaa-client-id))
            client_secret: ((uaa-client-secret))
            scopes: openid uaa.resource doppler.firehose cloud_controller.read
            auth_url: https://login.run.pivotal.io/oauth/authorize
            token_url: https://login.run.pivotal.io/oauth/token
            api_url: https://login.run.pivotal.io/userinfo
  - name: route_registrar
    release: routing
    consumes:
      nats:
        deployment: cf-cfapps-io2
        from: nats
    properties:
      route_registrar:
        routes:
        - name: grafana-metric-store
          tls_port: 3000
          registration_interval: 20s
          server_cert_domain_san: grafana
          uris:
          - grafana.observe.run.pivotal.io
releases:
- name: routing
  version: latest
- name: prometheus
  version: 26.2.0
- name: bpm
  version: latest
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 10
  canary_watch_time: 30000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-60000
addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm
variables:
- name: grafana_ssl
  type: certificate
  options:
    ca: /vpc-bosh-run-pivotal-io/cf-cfapps-io2/service_cf_internal_ca
    common_name: grafana
    extended_key_usage:
      - server_auth
