name: metric-store-grafana
features:
  converge_variables: true
instance_groups:
  name: grafana
  networks:
  - name: default
  stemcell: default
  vm_type: minimal
  persistent_disk_type: 1GB
  azs:
  - z1
  instances: 1
  jobs:
  - name: grafana
    release: grafana
    properties:
      grafana:
        security:
          admin_password: "((grafana_admin_password))"
          admin_username: admin
        server:
          root_url: https://grafana.observe.run.pivotal.io
        users:
          auto_assign_org_role: Editor
        auth:
          generic_oauth:
            name: UAA
            enabled: true
            allow_sign_up: true
            client_id: ((uaa-client-id))
            client_secret: ((uaa-client-secret))

            scopes:
              - openid
              - uaa.resource
              - doppler.firehose
              - logs.admin
              - cloud_controller.read

            auth_url: https://login.run.pivotal.io/oauth/authorize
            token_url: https://login.run.pivotal.io/oauth/token
            api_url: https://login.run.pivotal.io/userinfo
  - name: route_registrar
    release: routing
    properties:
      route_registrar:
        routes:
        - name: grafana-metric-store
          port: 3000
          registration_interval: 20s
          uris:
          - grafana.observe.run.pivotal.io
releases:
- name: routing
  version: latest
  name: prometheus-boshrelease
  version: latest
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 10
  canary_watch_time: 30000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-60000
variables:
  - name: grafana_admin_password
    type: password
