#!/usr/bin/env bash

set -eoux pipefail

. ./log-cache-ci/tasks/shared_bash


git config --global user.email "cf-log-cache+github@pivotal.io" && git config --global user.name "Metric Store CI"
set +x
if ! [[ -z "${GITHUB_PRIVATE_KEY}" ]]; then
  setup_github_ssh "${GITHUB_PRIVATE_KEY}"
fi
set -x

pushd repo
  unset GOPATH

  go mod tidy
  go mod vendor
  git add go.mod go.sum vendor
  git commit -m "Tidy dependencies"
popd
