---
platform: linux

inputs:
- name: metric-store-ci
- name: pivnet-metadata
- name: metric-store-backport

outputs:
- name: metric-store-backport-modified
- name: metric-store-backport-release

params:
  branch:
  JSON_KEY:

run:
  path: metric-store-ci/tasks/create-backport-metric-store-release/task
