name: metric-store-blackbox

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: metric-store
  version: latest
- name: bpm
  version: latest

instance_groups:
- name: metric-store-blackbox
  azs:
  - z2
  - z3
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: metric-store-blackbox
    release: metric-store
    properties:
      deployment: metric-store-blackbox
      source_id: metric-store
      cf_blackbox:
        enabled: true
        metric_store_address: https://metric-store.((sys_domain))
        client_id: ((pws-datadog-forwarder-client/Username))
        client_secret: ((pws-datadog-forwarder-client/Password))
      metric_store_metrics:
        tls:
          ca_cert: ((metric_store_metrics_server.ca))
          cert: ((metric_store_metrics_server.certificate))
          key: ((metric_store_metrics_server.private_key))
    consumes:
      metric-store: {from: metric-store, deployment: cf}
      cloud_controller: {from: cloud_controller, deployment: cf}
    provides:
      metric-store-blackbox: {as: metric-store-blackbox, shared: true}
  - name: bpm
    release: bpm

variables:
- name: metric_store_metrics_server
  type: certificate
  options:
    ca: /bosh-yuzu/cf/metric_scraper_ca
    common_name: metric-store
    alternative_names:
    - metric-store

update:
  canaries: 10
  canary_watch_time: 30000-60000
  max_in_flight: 10
  serial: true
  update_watch_time: 5000-60000
