---
platform: linux

inputs:
- name: metric-store-ci
- name: release-repo

outputs:
- name: committed-repo

run:
  path: ../metric-store-ci/tasks/commit/task
  dir: committed-repo

params:
  # - Required.
  # - The commit message.
  COMMIT_MESSAGE:
