#!/bin/bash
set -ex

cp -r ../release-repo/. .

if [ ! "$(git status --porcelain)" = "" ]; then
  git config user.email "cf-log-cache@pivotal.io"
  git config user.name "Log Cache CI"
  git add --all .

  git commit -m "$COMMIT_MESSAGE"
else
  echo "No changes to commit"
fi
