---
platform: linux

inputs:
  - name: metric-store-ci
  - name: slack-rate-limit-version
  - name: metadata

outputs:
  - name: modified-metadata

run:
  path: metric-store-ci/tasks/enable-disable-alert-success/run.sh
