resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: log-cache-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-release
    branch: develop
    private_key: {{github_key}}

- name: log-cache-deployments
  type: git
  source:
    uri: git@github.com:cloudfoundry/log-cache-deployments
    branch: master
    private_key: {{github_key}}

- name: log-cache-version
  type: semver
  source:
    bucket: loggregator-ci-versions
    key: log-cache
    access_key_id: {{loggregator-team-s3-access-key}}
    secret_access_key: {{loggregator-team-s3-secret-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_alert_webhook_url}}

jobs:
- name: log-cache-edge-deploy
  plan:
  - put: slack-alert
    params:
      silent: true
      username: {{slack_alert_username}}
      icon_url: {{slack_alert_icon_url}}
      channel: {{slack_alert_channel}}
      text: ":yellow_heart: Started :tree-log: Log Cache :tree-log: deployment to PWS Edge :knife:"
  - aggregate:
    - get: log-cache-release
    - get: log-cache-deployments
  - get: log-cache-version
    params: {pre: dev}
  - task: upload-log-cache
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          pushd log-cache-release
            cp ../log-cache-version/version src/
            bosh create-release --force
            bosh upload-release --rebase
          popd
      inputs:
      - name: log-cache-release
      - name: log-cache-version
  - task: log-cache-edge-deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        DEPLOYMENT_NAME: log-cache-edge
        MANIFEST_FILE: manifests/log-cache.yml
        SECRETS_FILE: shared-secrets.yml
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          bosh \
            interpolate "log-cache-release/$MANIFEST_FILE" \
            --ops-file "log-cache-deployments/pws/edge/log-cache-edge-ops-file.yml"

          bosh \
            deploy "log-cache-release/$MANIFEST_FILE" \
            --deployment "$DEPLOYMENT_NAME" \
            --non-interactive \
            --ops-file "log-cache-deployments/pws/edge/log-cache-edge-ops-file.yml"
      inputs:
      - name: log-cache-release
      - name: log-cache-deployments
  - put: log-cache-version
    params: {file: log-cache-version/version}
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: {{slack_alert_username}}
        icon_url: {{slack_alert_icon_url}}
        channel: {{slack_alert_channel}}
        text: ":green_heart: Finished :tree-log: Log Cache :tree-log: deployment to PWS Edge :knife:"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: {{slack_alert_username}}
        icon_url: {{slack_alert_icon_url}}
        channel: {{slack_alert_channel}}
        text: ":broken_heart: Failed to deploy :tree-log: Log Cache :tree-log: to PWS Edge :knife:
          Details here: https://log-cache.ci.cf-app.com/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
