#!/bin/bash

# vi:syntax=sh

set -ex

new_version=`cat release-version/version`
tag_name="v${new_version}"

pushd release-master
  git checkout master

  # commit version bump
  echo $new_version > src/version
  git add .
  git commit -m "Bump version to ${new_version}"

  bosh -n create-release --sha2 --final \
    --tarball ../release-tarball/release.tgz \
    --version "${new_version}"

  # commit release creation changes
  git add .
  git commit -m "Create final release"

  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  release_sha=$(git rev-parse @:./src/${SOURCE_PATH})
  git tag "${tag_name}" ${final_release_sha}

  cp -r . ../release-master-modified
popd

pushd release-develop
  git checkout develop
  git remote add -f local_master ../release-master
  git merge -v -m "Merge final release artifacts" "local_master/${final_release_abbrev}"

  cp -r . ../release-develop-modified
popd

pushd source-repo
  git tag "${tag_name}" ${release_sha}
  cp -r . ../source-repo-modified
popd
