#!/bin/bash

### TODO - rename task to tag and upload release or something

set -exu

if [[ -n ${BBL_STATE_DIR:-} ]]; then
  pushd "bbl-state/$BBL_STATE_DIR"
    eval "$(bbl print-env)"
  popd
fi

: ${BOSH_ENVIRONMENT:?must provide BOSH_* environment variables or BBL_STATE_DIR}

pushd bosh-release-dir
  configure-blobstore

  if [ "${RECORD_SHAS:-false}" == "true" ]; then
    git rev-parse HEAD > css_sha
    cat css_sha

    if [ -f go.mod ]; then
      set +e
      cat go.mod | grep cloudfoundry/metric-store-release | sed 's/.*-\([a-f0-9]*\)$/\1/g' > oss_sha
      cat oss_sha
      set -e
    fi
  fi

  if [ "${FORCE:-false}" == "true" ]; then
    bosh create-release --force
  else
    bosh create-release
  fi

  if [ "${NO_REBASE:-false}" = "true" ]; then
    bosh upload-release
  else
    bosh upload-release --rebase
  fi
popd
