#!/bin/bash -euf

# vi:syntax=sh

. ./metric-store-ci/tasks/shared_bash

RELEASE_VERSION=$(yq r pivnet-metadata/metadata.yml release.version)
TIMESTAMP=$(date +%s)

git config --global user.email "cf-log-cache+github@pivotal.io" && git config --global user.name "Metric Store CI"

pushd metric-store-master
  git checkout master
  echo_green "Adding SHA to metric-store-release"
  git rev-parse HEAD > sha
  echo "SHA: $(cat sha)"

  echo_green "BOSH creating metric-store-release ${RELEASE_VERSION}"

  # commit version bump
  write_version ${RELEASE_VERSION} src/internal/version
  git add .
  git commit -m "Bump version to ${RELEASE_VERSION}"

  # create release
  configure-blobstore

  bosh -n create-release --sha2 --final \
    --tarball ../metric-store-final-release/release-${RELEASE_VERSION}.tgz \
    --version "${RELEASE_VERSION}"

  # commit release creation changes
  echo_green "Committing final release and git tag on master"
  git add .
  git commit -m "Create final ${RELEASE_VERSION} release"

  tag_name="v${RELEASE_VERSION}"
  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  git tag "${tag_name}" ${final_release_sha}

  cp -r . ../metric-store-master-modified
popd

echo_green "Merging version and release artifacts to develop"
pushd metric-store-develop
  git checkout develop
  git remote add -f local_master ../metric-store-master
  git merge -v --no-ff -m "Merge final release artifacts" "local_master/${final_release_abbrev}"

  cp -r . ../metric-store-develop-modified
popd
