---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: metric-store-ci
- name: pivnet-metadata
- name: metric-store-develop
- name: metric-store-master

outputs:
- name: metric-store-master-modified
- name: metric-store-develop-modified
- name: metric-store-final-release

params:
  JSON_KEY:

run:
  path: metric-store-ci/tasks/create-final-metric-store-release/task
