#!/bin/bash

# vi:syntax=sh

set -ex

GO111MODULE=on go install github.com/mikefarah/yq/v3

RELEASE_VERSION=$(yq r release-version/metadata.yml release.version)
tag_name="v${RELEASE_VERSION}"

echo "${PROJECT_NAME} ${RELEASE_VERSION}" > github-release/name
echo ${tag_name} > github-release/tag
echo "TBD" > github-release/body
cp release-tarball/*.tgz github-release/
