#!/bin/bash

# vi:syntax=sh

set -ex

new_version=`cat release-version/version`
tag_name="v${new_version}"

echo "${PROJECT_NAME} ${new_version}" > github-release/name
echo ${tag_name} > github-release/tag
echo "TBD" > github-release/body
cp release-tarball/*.tgz github-release/
