name: metric-store-blackbox

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: metric-store
  version: latest
- name: loggregator-agent
  version: latest

instance_groups:
- name: metric-store-blackbox
  azs:
  - z1
  - z2
  - z3
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: metric-store-blackbox
    release: metric-store
    consumes:
      metric-store: {from: metric-store, deployment: default}
    properties:
      metric_store_metrics:
        tls:
          ca_cert: ((metric_store_metrics_server.ca))
          cert: ((metric_store_metrics_server.certificate))
          key: ((metric_store_metrics_server.private_key))
  - name: prom_scraper
    consumes:
      loggregator:
        deployment: cf-cfapps-io2
        from: loggregator
    release: loggregator-agent
    properties:
      scrape:
        tls:
          ca_cert: ((metric_store_metrics_client.ca))
          cert: ((metric_store_metrics_client.certificate))
          key: ((metric_store_metrics_client.private_key))
  - name: loggregator_agent
    consumes:
      doppler:
        deployment: cf-cfapps-io2
        from: doppler
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          agent:
            cert: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_tls_agent.certificate))"
            key: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_tls_agent.private_key))"
          ca_cert: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_ca.certificate))"

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true

variables:
- name: metric_store_ca
  options:
    common_name: metric-store
    is_ca: true
  type: certificate
- name: metric_store_metrics_server
  type: certificate
  options:
    ca: metric_store_ca
    common_name: metric-store
- name: metric_store_metrics_client
  type: certificate
  options:
    ca: metric_store_ca
    common_name: metric-store-client
