name: metric-store-edge-blackbox

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: metric-store
  version: latest
- name: loggregator-agent
  version: 5.3.6

instance_groups:
- name: metric-store-blackbox
  azs:
  - z2
  - z3
  instances: 2
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: pws-cf
  jobs:
  - name: metric-store-blackbox
    release: metric-store
    consumes:
      metric-store: {from: metric-store-edg, deployment: metric-store-edge}
      cloud_controller: {from: cloud_controller, deployment: cf-cfapps-io2}
    provides:
      metric-store-blackbox: {as: metric-store-edge-blackbox, shared: true}
    properties:
      source_id: metric-store-edge
      cf_blackbox:
        enabled: true
        metric_store_address: https://metric-store-edge.run.pivotal.io
        client_id: ((pws-datadog-forwarder-client/Username))
        client_secret: ((pws-datadog-forwarder-client/Password))
      metric_store_metrics:
        tls:
          ca_cert: ((metric_store_metrics_server.ca))
          cert: ((metric_store_metrics_server.certificate))
          key: ((metric_store_metrics_server.private_key))
  - name: prom_scraper
    consumes:
      loggregator:
        deployment: cf-cfapps-io2
        from: loggregator
    release: loggregator-agent
    properties:
      scrape:
        tls:
          ca_cert: ((prom_scraper_scrape_tls.ca))
          cert: ((prom_scraper_scrape_tls.certificate))
          key: ((prom_scraper_scrape_tls.private_key))
      metrics:
        ca_cert: ((prom_scraper_metrics_tls.ca))
        cert: ((prom_scraper_metrics_tls.certificate))
        key: ((prom_scraper_metrics_tls.private_key))
        server_name: prom_scraper_metrics
  - name: loggregator_agent
    consumes:
      doppler:
        deployment: cf-cfapps-io2
        from: doppler
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          agent:
            cert: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_tls_agent.certificate))"
            key: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_tls_agent.private_key))"
          ca_cert: "((/vpc-bosh-run-pivotal-io/cf-cfapps-io2/loggregator_ca.certificate))"
      metrics:
        ca_cert: ((loggregator_agent_metrics_tls.ca))
        cert: ((loggregator_agent_metrics_tls.certificate))
        key: ((loggregator_agent_metrics_tls.private_key))
        server_name: loggregator_agent

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true

variables:
- name: metric_store_ca
  options:
    common_name: metric-store
    is_ca: true
  type: certificate
- name: metric_store_metrics_server
  type: certificate
  options:
    ca: metric_store_ca
    common_name: metric-store
- name: loggregator_agent_metrics_tls
  type: certificate
  options:
    ca: metric_store_ca
    common_name: loggregator_agent
    extended_key_usage:
    - server_auth
- name: prom_scraper_metrics_tls
  type: certificate
  options:
    ca: metric_store_ca
    common_name: prom_scraper_metrics
    extended_key_usage:
    - server_auth
- name: prom_scraper_scrape_tls
  type: certificate
  options:
    ca: metric_store_ca
    common_name: prom_scraper
    extended_key_usage:
    - client_auth
