#!/bin/bash
set -exuo pipefail

GO111MODULE=on go install github.com/mikefarah/yq/v3

RELEASE_VERSION=$(yq r release-version/metadata.yml release.version)

source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars

pushd metric-store-deployments
  mkdir -p release-artifacts
  pushd release-artifacts
    bosh -d cf manifest > cf-manifest.yml
    git add .
  popd

  git commit --allow-empty -m "Save acceptance manifest for ${RELEASE_VERSION}"

  cp -r . ../metric-store-deployments-modified
popd

pushd release-version-generated
  echo "${RELEASE_VERSION}" > version
popd
