platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: metric-store-ci

run:
  path: metric-store-ci/tasks/add-credhub-vars/task

params:
  WEBHOOK_URL:

