#!/bin/bash
set -ex

pushd bbl-state/${BBL_STATE_DIR}
    eval "$(bbl print-env)"
popd

deployment=$(bosh environment --json | jq -r '.Tables[0].Rows[0].name')
path="/${deployment}/cf"
password=$(credhub get -n ${path}/cf_admin_password -j | jq -r ".value")

cf api api.$SYSTEM_DOMAIN --skip-ssl-validation
cf auth admin "${password}"
cf target -o system

set +e
cf org $ORG
set -e
if [ $? -eq 0 ]; then
  cf create-org $ORG
fi
cf target -o $ORG

set +e
cf space $SPACE
set -e
if [ $? -eq 0 ]; then
  cf create-space $SPACE
fi
cf target -s $SPACE
