#!/bin/bash
set -ex

source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars

cf api api.$SYSTEM_DOMAIN --skip-ssl-validation
cf auth admin "$(get_password_from_credhub cf_admin_password)"
cf target -o system

set +e
cf org $ORG
set -e
if [ $? -eq 0 ]; then
  cf create-org $ORG
fi
cf target -o $ORG

set +e
cf space $SPACE
set -e
if [ $? -eq 0 ]; then
  cf create-space $SPACE
fi
cf target -s $SPACE
