---
platform: linux

inputs:
- name: metric-store-ci
- name: repo
- name: golang-release-repo

run:
  path: metric-store-ci/tasks/bump-golang-release/task

params:
  GITHUB_REPO:
  GITHUB_EMAIL:
  GITHUB_AUTH_TOKEN:
  GITHUB_PRIVATE_KEY:
  GOLANG_PACKAGE_VERSION: "1.21"
  JSON_KEY:
