groups:
- name: all
  jobs:
  - refresh-environments
  - build-docker-images
- name: dependencies
  jobs:
  - go-dependencies

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: metric-store-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/ms_github_private_key))
    ignore_paths:
    - .final_builds
    - releases
    disable_ci_skip: false
    clean_tags: true

- name: metric-store-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

- name: docker-images
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/ms_github_private_key))
    paths:
    - docker-images

- name: metric-store-tile-image
  type: docker-image
  source:
    repository: gcr.io/cf-loggregator-log-cache/metric-store-tile
    username: _json_key
    password: ((release-credentials.yml/Notes/gcp-service-account-key))

- name: after-standup
  type: time
  source:
    interval: 23h
    location: America/Denver
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    start: 9:06 AM
    stop: 5:00 PM

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_high_visibility_alert_webhook_url))

jobs:
- name: build-docker-images
  serial: true
  public: true
  plan:
  - get: metric-store-ci
  - get: metric-store-develop
  - get: docker-images
    trigger: true
  - task: build-metric-store-tile-image
    file: metric-store-ci/tasks/build-go-docker-image/task.yml
    input_mapping:
      context-repo: docker-images
      source-repo: metric-store-develop
    output_mapping:
      build-image: build-metric-store-tile-image
    params:
      CONTEXT_PATH: docker-images/metric-store-tile
      BASE_PACKAGE: ..
  - put: metric-store-tile-image
    params:
      build: build-metric-store-tile-image/build
      tag: build-metric-store-tile-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: refresh-environments
  plan:
  - in_parallel:
    - get: metric-store-ci
    - get: after-standup
      trigger: true
    - get: cf-deployment-concourse-tasks-image
  - in_parallel:
    - task: refresh-yubacity
      image: cf-deployment-concourse-tasks-image
      file: metric-store-ci/tasks/refresh-env/task.yml
      params:
        ID: 575

- name: go-dependencies
  serial: true
  plan:
    - in_parallel:
        - get: metric-store-develop
        - get: metric-store-ci
        - get: cf-deployment-concourse-tasks-image
    - task: outdated
      timeout: 15m
      image: cf-deployment-concourse-tasks-image
      file: metric-store-ci/tasks/go-dependencies-check/task.yml
  on_success:
    do:
      - put: slack-alert
        params:
          silent: true
          text: ":warning: New Metric Store go dependency updates are found"
