groups:
- name: all
  jobs:
  - refresh-environments
  - build-docker-images
  - action-items

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest


resources:
- name: metric-store-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-release
    branch: develop
    private_key: ((github-key-ci.yml/Notes/ms_github_private_key))
    ignore_paths:
    - .final_builds
    - releases
    disable_ci_skip: false
    clean_tags: true

- name: metric-store-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

- name: docker-images
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/ms_github_private_key))
    paths:
    - docker-images

- name: tile-image
  type: docker-image
  source:
    repository: logcache/metric-store-tile
    username: ((docker-hub-ci.yml/Notes/docker-hub-username))
    password: ((docker-hub-ci.yml/Notes/docker-hub-password))

- name: daily
  type: time
  source:
    interval: 24h

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_high_visibility_alert_webhook_url))

- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/pivotal-cf/concourse-tasks
    branch: master

- name: after-standup
  type: time
  source:
    interval: 23h
    location: America/Denver
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    start: 9:06 AM
    stop: 5:00 PM

jobs:
- name: build-docker-images
  serial: true
  public: true
  plan:
  - get: metric-store-ci
  - get: metric-store-develop
  - get: docker-images
    trigger: true
  - task: build-metric-store-tile-image
    file: metric-store-ci/tasks/build-go-docker-image/task.yml
    input_mapping:
      context-repo: docker-images
      source-repo: metric-store-develop
    output_mapping:
      build-image: build-metric-store-tile-image
    params:
      CONTEXT_PATH: docker-images/metric-store-tile
      BASE_PACKAGE: ..
  - put: tile-image
    params:
      build: build-metric-store-tile-image/build
      tag: build-metric-store-tile-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: refresh-environments
  plan:
  - in_parallel:
    - get: metric-store-ci
    - get: daily
      trigger: true
    - get: cf-deployment-concourse-tasks-image
  - in_parallel:
    - task: refresh-marina
      tags: [ cf-denver-shared-vsphere ]
      image: cf-deployment-concourse-tasks-image
      file: metric-store-ci/tasks/refresh-env/task.yml
      params:
        ID: 354
    - task: refresh-manila
      tags: [ cf-denver-shared-vsphere ]
      image: cf-deployment-concourse-tasks-image
      file: metric-store-ci/tasks/refresh-env/task.yml
      params:
        ID: 66

- name: action-items
  plan:
  - in_parallel:
    - get: concourse-tasks
    - get: after-standup
      trigger: true

  - task: create-action-item-reminder
    file: concourse-tasks/postfacto/slack-action-items/task.yml
    params:
      POSTFACTO_RETRO_URL: ((postfacto.yml/Notes/retro_url))
      POSTFACTO_API_URL: ((postfacto.yml/Notes/api_url))
      POSTFACTO_PASSWORD: ((postfacto.yml/Notes/password))

  - put: slack-alert
    params:
      attachments_file: alert/attachments
      username: postfacto
      icon_emoji: ":ballot_box_with_check:"

