groups:
- name: all
  jobs:
  - refresh-environments

resources:
- name: metric-store-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

- name: daily
  type: time
  source:
    interval: 24h

jobs:
- name: refresh-environments
  plan:
  - get: metric-store-ci
  - get: daily
    trigger: true
  - get: cf-deployment-concourse-tasks-image
  - task: refresh-marina
    tags: [ cf-denver-shared-vsphere ]
    image: cf-deployment-concourse-tasks-image
    file: metric-store-ci/tasks/refresh-env/task.yml
    params:
      ID: 354
