resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0

resources:
- name: osspi-tool
  type: git
  icon: gitlab
  source:
    branch: main
    uri: git@gitlab.eng.vmware.com:source-insight-tooling/norsk-to-osspi.git
    private_key: ((metric-store.gitlab-private-key))

- name: metric-store-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-release
    branch: master
    private_key: ((metric-store.svcboteos_github_private_key))

jobs:
- name: metric-store-scan
  serial: true
  plan:
  - in_parallel:
    - get: osspi-tool
    - get: metric-store-repo
      trigger: true
      params: { submodules: all }
  - task: osspi-scan-metric-store-repo
    file: osspi-tool/tasks/osspi/run-osspi-source.yaml
    input_mapping:
      repo1: osspi-tool
      repo2: metric-store-repo
    params:
      REPO: repo2
      OSM_ENVIRONMENT: ((osm-environment))
      API_KEY: ((metric-store.osspi-apikey-((osm-environment))))
      USERNAME: ((metric-store.osspi-user-((osm-environment))))
      PRODUCT: p-metric-store
      VERSION: ((tile-version))
      OSM_PACKAGE_GROUP_NAME: metric-store-repo
      PREPARE: |
        go mod vendor
      OSSPI_SCANNING_PARAMS: |
        enable: true
        include_bomtools: "go_mod"
        search_depth: 5
        go_mod.path: "/go/bin/go"
        
        # exclude for signature scans
        exclude_patterns:
          - metric-store-repo/vendor
      OSSPI_IGNORE_RULES: |
        - name_regex: onsi\/ginkgo
          version_regex: .*
        - name_regex: gomega
          version_regex: .*