############## Resource Types ################
resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.5.1

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

#### Secure Release Pipeline resource type
- name: build-metadata
  type: registry-image
  source:
    repository: pcfopsmanager/build-metadata-resource

############## Resources ################
resources:
#### Secure Release Pipeline resources
- name: srp-helper-test
  type: registry-image
  source:
    repository: harbor.dhaka.cf-app.com/srp/srp-helper-task
    username: ((phoenix-osspi.srp-harbor-username))
    password: ((phoenix-osspi.srp-harbor-password))

- name: build-metadata
  type: build-metadata

- name: metric-store-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-ci
    private_key: ((phoenix-osspi.svcboteos_github_private_key))
    branch: Add-SRP-resource-to-pipeline

- name: metric-store-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/metric-store-release
    branch: fast-test-develop
    private_key: ((phoenix-osspi.svcboteos_github_private_key))
    ignore_paths:
    - .final_builds
    - releases
    disable_ci_skip: false
    clean_tags: true

- name: metric-store-version
  type: semver
  source:
    driver: gcs
    bucket: metric-store-ci-versions
    key: test/metric-store-release-acceptance-tile
    json_key: ((phoenix-osspi.gcp_service_account_key))
    initial_version: 0.2.0-build.24



############## Jobs ################
jobs:
##### Secure Release Pipeline jobs
- name: "collect-source-provenance"
  serial: true
  plan:
    - in_parallel:
        - get: srp-helper-test
        - get: build-metadata
        - get:  metric-store-version
        - get: metric-store-develop
        - get: metric-store-ci
    - task: "submit-metadata-for-metric-store-release"
      image: srp-helper-test
      config:
        platform: linux
        inputs:
          - name: metric-store-ci
          - name: metric-store-develop
          - name: build-metadata
          - name: metric-store-version
        params:
          SRP_CLIENT_ID: ((phoenix-osspi.srp-client-id))
          SRP_CLIENT_SECRET: ((phoenix-osspi.srp-client-secret))
          SRP_URL: https://srp.vmware.com
        run:
          path: /bin/bash
          args:
            - -c
            - |
              set -x
              set -euo pipefail
              mkdir ./provenance

              VERSION=$(cat metric-store-version/version)
              BUILD_NUMBER=$(cat build-metadata/build-name)
              BUILD_PIPELINE_NAME=$(cat build-metadata/build-pipeline-name)
              BUILD_JOB_NAME=$(cat build-metadata/build-job-name)
              BUILD_ID=$(cat build-metadata/build-id)
              COMP_UID="uid.obj.build.concourse(instance='concourse.cf-denver.com',namespace='metric-store-log-cache',pipeline='$BUILD_PIPELINE_NAME',job='$BUILD_JOB_NAME',build_id='$BUILD_ID')"
              OUTPUT_VERSION="3.2.1-${BUILD_PIPELINE_NAME}"

              srp --version
              srp provenance source \
                --scm-type git \
                --name "metric-store-develop" \
                --path metric-store-develop \
                --saveto ./provenance/source.json \
                --build-number "$BUILD_NUMBER" \
                --version "$VERSION" \
                --all-ephemeral true \
                --build-type release \
                --comp-uid "$COMP_UID"

              srp config auth \
                --client-id $SRP_CLIENT_ID \
                --client-secret $SRP_CLIENT_SECRET \
                --srp-endpoint $SRP_URL

              export SRP_WORKING_DIR=~/tmp/srp-work

              srp provenance init
              srp provenance add-build gitlab --namespace 'metric-store-log-cache' --project 'metric-store-ci' --pipeline-id $BUILD_ID
              srp provenance action start --name metric-store-build-action

              curl https://build-artifactory.eng.vmware.com/osspicli-local/observer/linux-observer-2.0.0.tar.gz &&
              mkdir ~/.observerz
              cd ~/.observer
              tar zxf /path/to/download/linux-observer-2.0.0.tar.gz

              # in current versions, we require user set JAVA_HOME like
              # if you do not have java in the env, please mount toolchain
              # in future release, we will skip java config if not detected
              export JAVA_HOME=/build/toolchain/lin64/jdk-1.8.0_191

              # set alias
              alias observer_agent=~/.observer/bin/observer_agent.bash
              observer_agent --version

              observer_agent -m start_observer --output_environment envs.sh --env_to_shell
              source ./envs.sh

              srp util env --saveto=${SRP_WORKING_DIR}/build-env.json

              echo " ===> ARTIFACTORY_AUTH_TOKEN is not set, skipping publish to artifactory!!!"

              echo " ===> Stopping observer and cleaning up"
              source ./envs.sh unset

              observer_agent -m stop_observer -f ${SRP_WORKING_DIR}/network_provenance.json
              cat ${SRP_WORKING_DIR}/network_provenance.json
              rm -f envs.sh

              srp provenance action import-cmd  --cmd '_build_under_observer.sh' --env-file=${SRP_WORKING_DIR}/build-env.json

              echo "==========> srp provenance action import-observation"
              srp provenance action stop
              echo "==========> srp provenance action stop"

              export APP_JAR="srp-example-gradle-${OUTPUT_VERSION}-SNAPSHOT.jar"

              echo "==========> Creating srp_schematic.yaml"
              echo "==========> Creation of srp_schematic.yaml file was done."

              srp provenance compile --saveto ${SRP_WORKING_DIR}/prov3_fragment.json
              echo "==========> Created ${SRP_WORKING_DIR}/prov3_fragment_${BUILD_ID}.json"

              DTR=`cat ${SRP_WORKING_DIR}/distance-to-root`
              echo "==========> calculated DTR='${DTR}', git rev-list --count HEAD=$(git rev-list --count HEAD)"

              if [ "${SRP_CLIENT_ID}" != "" ] && [ "${SRP_CLIENT_SECRET}" != "" ]; then
                echo "==========> Start"
                srp provenance submit --verbose --path ${SRP_WORKING_DIR}/prov3_fragment.json
                echo "==========> Stop"
              else
                echo "==========> Skipping SRP submission.  Both SRP_CLIENT_ID and SRP_CLIENT_SECRET must be defined"
              fi

              srp metadata status \
                --srp-endpoint $SRP_URL

              srp metadata submit \
                -p ./provenance/source.json \
                -u "uid.mtd.provenance_3_0.fragment(obj_uid=$COMP_UID,revision='')" \
                --srp-endpoint $SRP_URL

              srp metadata get \
                --uid "uid.mtd.provenance_3_0.fragment(obj_uid=$COMP_UID,revision='')"
