#!/bin/bash

# vi:syntax=sh

set -ex

. ./log-cache-ci/tasks/shared_bash

new_version=`cat release-version/version`
tag_name="v${new_version}"

git config --global user.email "cf-log-cache+github@pivotal.io" && git config --global user.name "Metric Store CI"
set +x
if ! [[ -z "${GITHUB_PRIVATE_KEY}" ]]; then
  setup_github_ssh "${GITHUB_PRIVATE_KEY}"
fi
set -x

pushd release-master
  git checkout master

  # commit version bump
  echo $new_version > version
  git add .
  git commit -m "Bump version to ${new_version}"

  # create release
  cat << EOF > config/private.yml
---
blobstore:
  options:
    credentials_source: static
    json_key: |
      $(echo ${JSON_KEY})
EOF

  if [ "${RECORD_SHAS:-false}" == "true" ]; then
    git rev-parse HEAD > css_sha
    cat css_sha

    if [ -f go.mod ]; then
      set +e
      cat go.mod | grep cloudfoundry/metric-store-release | sed 's/.*-\([a-f0-9]*\)$/\1/g' > oss_sha
      cat oss_sha
      set -e
    fi
  fi

  bosh -n create-release --sha2 --final \
    --tarball ../release-tarball/release.tgz \
    --version "${new_version}"

  # commit release creation changes
  git add .
  git commit -m "Create release ${new_version}"

  release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  release_sha=$(git rev-parse HEAD)
  git tag "${tag_name}" ${release_sha}

  cp -r . ../release-master-modified
popd

pushd release-develop
  git checkout develop
  git remote add -f local_master ../release-master
  git merge -v --no-ff -m "Merge release ${new_version} artifacts" "local_master/${release_abbrev}"

  cp -r . ../release-develop-modified
popd
