resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.24.0

- name: log-store-release-repo
  type: git
  source:
    uri: git@github.com:pivotal/log-store-release
    branch: master
    private_key: ((github-key-ci.yml/Notes/github_key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-ci.yml/Notes/slack_high_visibility_alert_webhook_url))

jobs:
- name: log-store-deploy
  serial: true
  serial_groups: [chaos]
  plan:
  - aggregate:
    - get: log-store-release-repo
      trigger: false
    - get: cf-deployment-concourse-tasks-image
  - put: slack-alert
    params:
      silent: true
      username: ((slack-ci.yml/Notes/slack_alert_username))
      icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
      channel: ((slack-ci.yml/Notes/slack_high_visibility_alert_channel))
      text: ":yellow_heart: Started :tree-log: Log Store deployment to :knife: PWS Prod"
  - task: upload-release
    file: log-store-release-repo/ci/tasks/upload-release/task.yml
    image: cf-deployment-concourse-tasks-image
    input_mapping:
      bosh-release-dir: log-store-release-repo
    params:
      BOSH_CA_CERT: ((bosh-ca-cert.certificate))
      BOSH_CLIENT: ((bosh-admin-client.username))
      BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
      BOSH_ENVIRONMENT: bosh.run.pivotal.io
  - task: deploy
    image: cf-deployment-concourse-tasks-image
    config:
      platform: linux
      inputs:
      - name: log-store-release-repo
      params:
        BOSH_CA_CERT: ((bosh-ca-cert.certificate))
        BOSH_CLIENT: ((bosh-admin-client.username))
        BOSH_CLIENT_SECRET: ((bosh-admin-client.password))
        BOSH_ENVIRONMENT: bosh.run.pivotal.io
        BOSH_DEPLOYMENT: log-store
        AUTH_PROXY_CLIENT_ID: ((log-store-cf-auth-proxy-client.username))
        AUTH_PROXY_CLIENT_SECRET: ((log-store-cf-auth-proxy-client.password))
        BLACKBOX_CLIENT_ID: ((pws-datadog-forwarder-client/Username))
        BLACKBOX_CLIENT_SECRET: ((pws-datadog-forwarder-client/Password))
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -eux

          bosh deploy "log-store-release-repo/manifests/log-store-edge.yml" \
            --var auth-proxy-client-id="$AUTH_PROXY_CLIENT_ID" \
            --var auth-proxy-client-secret="$AUTH_PROXY_CLIENT_SECRET" \
            --var blackbox-client-id="$BLACKBOX_CLIENT_ID" \
            --var blackbox-client-secret="$BLACKBOX_CLIENT_SECRET" \
            --ops-file log-store-release-repo/manifests/ops-files/prod.yml \
            --non-interactive
  on_success:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_high_visibility_alert_channel))
        text: ":green_heart: Finished :tree-log: Log Store deployment to :knife: PWS Prod"
  on_failure:
    do:
    - put: slack-alert
      params:
        silent: true
        username: ((slack-ci.yml/Notes/slack_alert_username))
        icon_url: ((slack-ci.yml/Notes/slack_alert_icon_url))
        channel: ((slack-ci.yml/Notes/slack_high_visibility_alert_channel))
        text: ":broken_heart: Failed to deploy :tree-log: Log Store: to :knife: PWS Prod"

