product-name: metric-store
network-properties:
  network:
    name: manila-management-subnet
  other_availability_zones:
    - name: us-central1-f
    - name: us-central1-f
    - name: us-central1-f
  singleton_availability_zone:
    name: us-central1-f
resource-config:
  metric-store:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    elb_names: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
product-properties:
  .properties.pks_cluster_discovery:
    selected_option: enabled
    value: enabled
  .properties.pks_cluster_discovery.enabled.cluster_discovery_scrape_port:
    value: 9096
  .properties.pks_cluster_discovery.enabled.disabled:
    value: true
  .properties.pks_cluster_discovery.enabled.discovery_frequency_seconds:
    value: 600
  .properties.pks_cluster_discovery.enabled.enabled:
    value: false
  .properties.pks_cluster_discovery.enabled.pks_skip_ssl_validation:
    value: true
  .properties.pks_cluster_discovery.enabled.pks_ca:
    value: |-
