#!/bin/bash

set -exu

source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars

arguments=""
for o in $OPS_FILES; do
  arguments="$arguments --ops-file ops-files/$o"
done

for v in $VARS_FILES; do
  arguments="$arguments --vars-file vars-files/$v"
done

bosh -d "$DEPLOYMENT_NAME" -n deploy "bosh-release/$MANIFEST_FILE" $arguments

bosh -n clean-up --all
