#!/bin/bash

# vi:syntax=sh

set -ex

new_version=`cat log-cache-release-version/version`
tag_name="v${new_version}"

pushd log-cache-release-master
  git checkout master

  # commit version bump
  echo $new_version > src/version
  git add .
  git commit -m "Bump version to ${new_version}"

  # create release
  cat << EOF > config/private.yml
---
blobstore:
  options:
    credentials_source: static
    json_key: |
      $(echo ${JSON_KEY})
EOF

  bosh -n create-release --sha2 --final \
    --tarball ../release-tarball/release.tgz \
    --version "${new_version}"

  # commit release creation changes
  git add .
  git commit -m "Create final release"

  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  log_cache_release_sha=$(git rev-parse @:./src/code.cloudfoundry.org/log-cache)
  git tag "${tag_name}" ${final_release_sha}

  cp -r . ../log-cache-release-master-modified
popd

pushd log-cache-release-develop
  git checkout develop
  git remote add -f local_master ../log-cache-release-master
  git merge -v --no-ff -m "Merge final release artifacts" "local_master/${final_release_abbrev}"

  cp -r . ../log-cache-release-develop-modified
popd

pushd log-cache
  git tag "${tag_name}" ${log_cache_release_sha}
  cp -r . ../log-cache-modified
popd
