#!/bin/bash

# vi:syntax=sh

set -ex

new_version=`cat log-cache-release-version/version`
tag_name="v${new_version}"

echo "Log Cache ${new_version}" > github-release/name
echo ${tag_name} > github-release/tag
echo "TBD" > github-release/body

pushd log-cache-release-master
  git checkout master
  cat << EOF > config/private.yml
---
blobstore:
  provider: s3
  options:
    bucket_name: log-cache-release-blobs
    access_key_id: ${S3_ACCESS_KEY}
    secret_access_key: ${S3_SECRET_KEY}
    credentials_source: static
EOF

  bosh -n create-release --sha2 --final \
    --tarball ../github-release/release.tgz \
    --version "${new_version}"
  git add .
  git commit -m "Create final release"

  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  git tag "${tag_name}" ${final_release_sha}

  cp -r . ../log-cache-release-master-modified
popd

pushd log-cache-release-develop
  git checkout develop
  git remote add -f local_master ../log-cache-release-master
  git merge -v -m "Merge final release artifacts" "local_master/${final_release_abbrev}"

  cp -r . ../log-cache-release-develop-modified
popd
