---
platform: linux

inputs:
  - name: metric-store-ci
  - name: pivnet-metadata
  - name: metric-store-master
  - name: stemcell
  - name: bpm-release
  - name: bosh-dns-aliases-release
  - name: cf-routing-release
  - name: metric-store-final-release

outputs:
  - name: baked-tile

params:
  TILE_NAME: metric-store

run:
  path: metric-store-ci/tasks/tile_bake_final/task
