---
platform: linux

inputs:
  - name: metric-store-ci
  - name: pivnet-metadata
  - name: p-metric-store-release-master
  - name: stemcell
  - name: bpm-release
  - name: cf-routing-release
  - name: metric-store-final-bosh-release

outputs:
  - name: baked-tile

params:
  TILE_NAME: metric-store

run:
  path: metric-store-ci/tasks/tile_bake_final/task
