#!/bin/bash -euf

. ./log-cache-ci/tasks/shared_bash

RELEASE_VERSION=$(cat release-version/version)
TIMESTAMP=$(date +%s)

mkdir -p releases

echo_green "Copying depedency releases to releases directory"
cp p-metric-store-final-bosh-release/p-metric-store-release.tgz releases/p-metric-store-release.tgz
cp oss-metric-store-final-bosh-release/oss-metric-store-release.tgz releases/oss-metric-store-release.tgz
mv bpm-release/release.tgz releases/bpm-release.tgz
mv cf-routing-release/release.tgz releases/cf-routing-release.tgz
mv loggregator-agent-release/release.tgz releases/loggregator-agent-release.tgz

STEMCELL_VERSION=$(cat stemcell/version)
echo "Using stemcell ${STEMCELL_VERSION} ..."
pushd p-metric-store-release-repo/tile
  erb -v stemcell_version="${STEMCELL_VERSION}" metadata.yml.erb > metadata.yml
popd

mkdir -p baked-tile
TILE_FILE=baked-tile/${TILE_NAME}-${RELEASE_VERSION}-${TIMESTAMP}.pivotal

echo_green "Kiln baking tile"

kiln bake \
    --version "$RELEASE_VERSION" \
    --metadata p-metric-store-release-master/tile/metadata.yml \
    --icon p-metric-store-release-master/tile/icon.png \
    --releases-directory releases \
    --properties-directory p-metric-store-release-master/tile/properties \
    --jobs-directory p-metric-store-release-master/tile/jobs \
    --instance-groups-directory p-metric-store-release-master/tile/instance_groups \
    --bosh-variables-directory p-metric-store-release-master/tile/variables \
    --output-file ${TILE_FILE}

echo_green "Freshly baked tile 🍞: ${TILE_FILE}"
