#!/bin/bash

# vi:syntax=sh

set -ex

new_version=`cat log-cache-release-version-backport/version`
tag_name="v${new_version}"

echo "Log Cache ${new_version}" > github-release/name
echo ${tag_name} > github-release/tag
echo "TBD" > github-release/body

pushd log-cache-release-backport
  git checkout "${BACKPORT_BRANCH}"

  # commit version bump
  echo $new_version > src/version
  git add .
  git commit -m "Bump version to ${new_version}"

  # create release
  cat << EOF > config/private.yml
---
blobstore:
  provider: s3
  options:
    bucket_name: log-cache-release-blobs
    access_key_id: ${S3_ACCESS_KEY}
    secret_access_key: ${S3_SECRET_KEY}
    credentials_source: static
EOF

  bosh -n create-release --sha2 --final \
    --tarball ../github-release/release.tgz \
    --version "${new_version}"

  # commit release creation changes
  git add .
  git commit -m "Create final release"

  git tag "${tag_name}" HEAD

  cp -r . ../log-cache-release-backport-modified
popd

pushd log-cache-release-master
  git checkout master
  git remote add -f local_backport ../log-cache-release-backport
  echo '** merge=union' >> .gitattributes
  git cherry-pick "local_backport/${BACKPORT_BRANCH}"
  rm .gitattributes

  cp -r . ../log-cache-release-master-modified
popd

pushd log-cache-release-develop
  git checkout develop
  git remote add -f local_master ../log-cache-release-master
  git merge -v -m "Merge final release artifacts" local_master/master

  cp -r . ../log-cache-release-develop-modified
popd
