#!/bin/bash -euf
. ./metric-store-ci/tasks/shared_bash

this_major_minor=$(major_minor_from_semver `cat this-version/version`)
main_major_minor=$(major_minor_from_semver `cat main-version/version`)

if [[ "$this_major_minor" == "$main_major_minor" ]]; then
  echo "major-minor version matches"
  cp this-version/version new-main-version/
else
  echo "major-minor version mis-match"
  echo "${main_major_minor}.1" > new-main-version/version
fi
