---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: metric-store-ci
- name: linked-repo

run:
  path: metric-store-ci/tasks/create-tracker-story/task

params:
  TRACKER_API_TOKEN:
  TRACKER_PROJECT_ID:
  TRACKER_STORY_TYPE:
  TRACKER_STORY_NAME:
  TRACKER_STORY_DESCRIPTION:
  GITHUB_REPO:
