#!/bin/bash

set -exu

. ./log-cache-ci/tasks/shared_bash

pushd linked-repo
  linked_repo_sha=$(git rev-parse HEAD)
popd

cat << EOF > new_story.json
  {
    "story_type":"${TRACKER_STORY_TYPE}",
    "name":"${TRACKER_STORY_NAME}",
    "description":"
      ${TRACKER_STORY_DESCRIPTION}

      Commit: https://github.com/${GITHUB_REPO}/commit/${linked_repo_sha}
    "
  }
EOF

curl -X POST \
  -H "X-TrackerToken: $TRACKER_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d "@new_story.json" \
  https://www.pivotaltracker.com/services/v5/projects/$TRACKER_PROJECT_ID/stories
