platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

inputs:
- name: version
- name: metric-store-ci

outputs:
- name: messages

run:
  path: metric-store-ci/tasks/alert-message-release-end/task
