---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: metric-store-ci
- name: repo

run:
  path: metric-store-ci/tasks/bump-dependencies/task

params:
  GITHUB_REPO:
  GITHUB_USER:
  GITHUB_AUTH_TOKEN:
  GITHUB_PRIVATE_KEY:
  EXCEPT:
