#!/usr/bin/env bash

set -eoux pipefail

. ./log-cache-ci/tasks/shared_bash

timestamp=$(date +%Y-%m-%d-%H%M%S)

set +eu
. /usr/local/share/chruby/chruby.sh
chruby 2.6.2
set -eu

gem install bundler

git config --global user.email "cf-log-cache+github@pivotal.io" && git config --global user.name "Metric Store CI"
set +x
if ! [[ -z "${GITHUB_PRIVATE_KEY}" ]]; then
  setup_github_ssh "${GITHUB_PRIVATE_KEY}"
fi
set -x

pushd repo
  git checkout -b bump-dependencies-${timestamp}
  cat <<EOF > Gemfile
  source 'https://rubygems.org'

  gem 'lapidarist', git: 'https://github.com/attack/lapidarist.git', branch: 'go-mod'
EOF

  bundle install
  unset GOPATH

  # pre-clean up go.mod
  go mod tidy
  go mod vendor

  set +e
  git add go.mod go.sum vendor
  git commit -m "Tidy dependencies"
  set -e

  bundle exec lapidarist -d . -t 'scripts/test unit' -r --debug --go --except ${EXCEPT} | tee lapidarist.out
  pull_request_body=$(cat lapidarist.out | sed -n '/Summary/,$p' | grep -v "\- skipped" | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')

  git push origin bump-dependencies-${timestamp}
popd

cat << EOF > new_pull_request.json
  {
    "title": "Auto Bump Dependencies ${timestamp}",
    "base": "develop",
    "head": "bump-dependencies-${timestamp}",
    "body": "$(echo "${pull_request_body}")"
  }
EOF

cat new_pull_request.json

curl -X POST \
  -H "Authorization: token ${GITHUB_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  --data-binary @new_pull_request.json \
  https://api.github.com/repos/${GITHUB_REPO}/pulls
