---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: logcache/base

inputs:
- name: metric-store-ci # - This repo
- name: source-repo    # - The Go package to test

run:
  path: metric-store-ci/tasks/go-test-module/task
