# cat <<EOT >> ops-files/cf-PR-log-cache-router-tls.yml
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-cf-auth-proxy/properties/external_cert?
  value: "((logcache_ssl.certificate))"
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-cf-auth-proxy/properties/external_key?
  value: "((logcache_ssl.private_key))"
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar?
  value:
    name: route_registrar
    release: routing
    properties:
      route_registrar:
        routes:
        - name: log-cache-reverse-proxy
          tls_port: 8083
          registration_interval: 20s
          server_cert_domain_san: log-cache.((system_domain))
          uris:
          - log-cache.((system_domain))
          - "*.log-cache.((system_domain))"
# cat <<EOT >> ops-files/cf-deployment-log-cache-candidate-changes.yml
- type: replace
  path: /variables/name=logs_provider
  value:
    name: log_cache_to_logs_provider
    type: certificate
    options:
      ca: loggregator_ca
      common_name: log-cache
      extended_key_usage:
      - client_auth
- type: replace
  path: /variables/name=log_cache_to_loggregator_agent?
  value:
    name: log_cache_to_loggregator_agent
    type: certificate
    options:
      ca: loggregator_ca
      common_name: log-cache
      extended_key_usage:
      - client_auth
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-nozzle/properties/logs_provider/tls
  value:
    ca_cert: "((log_cache_to_logs_provider.ca))"
    cert: "((log_cache_to_logs_provider.certificate))"
    key: "((log_cache_to_logs_provider.private_key))"

