#!/bin/bash

function set_globals {
    pipeline=$1
    pipeline_ext='.yml'
    pipeline_dir='pipelines/pws/'
    pipeline_name=$(echo "pws/${pipeline}" | sed 's/\//-/g')
    config_path=${pipeline_dir}${pipeline}${pipeline_ext}
    TARGET="${TARGET:-pws}"
}

function validate_usage {
    if [[ "$pipeline" == pws* ]]; then
        echo "the leading 'pws/' is not needed"
        exit 1
    fi

    if [ "$pipeline" = "-h" ] || [ "$pipeline" = "--help" ] || [ -z "$pipeline" ] || [[ "$pipeline" == pws* ]]; then
        print_usage
        exit 1
    fi
}

function validate_pipeline {
    echo -n "Validating '${pipeline}' pipeline ... "

    fly -t ${TARGET} validate-pipeline -c ${config_path}
    pipeline_valid=$?

    return $pipeline_valid
}

function sync_fly {
    fly -t $TARGET sync
}

function reconfigure_pipeline {
    echo "Reconfiguring '${pipeline_name}' pipeline ..."

    reconfigure-pipeline \
      --target ${TARGET} \
      --pipeline ${pipeline_name} \
      --config ${config_path}
}

function print_usage {
    echo "usage: $0 <pipeline (without leading pws)>"
}

function main {
    set_globals $1
    validate_usage
    validate_pipeline
    sync_fly

    if [ $? -eq 0 ]; then
        reconfigure_pipeline
    fi
}

main $1
