#!/bin/bash

function set_globals {
    pipeline=$1
    TARGET="${TARGET:-pws}"
}

function validate {
    if [ "$pipeline" = "-h" ] || [ "$pipeline" = "--help" ] || [ -z "$pipeline" ]; then
        print_usage
        exit 1
    fi
}

function set_pipeline {
    lpass show --note "Shared-Loggregator (Pivotal Only)/pipeline-secrets.yml" > shared-secrets.yml
    lpass show --note "Shared-CF- Log Cache (Pivotal ONLY)/hdub-github-key.yml" > github-key.yml
    lpass show --note "Shared-CF- Log Cache (Pivotal ONLY)/datadog-api-key-pws.yml" > datadog-api-key.yml

    PIPELINE_NAME=$(echo $1 | sed 's/\//-/g')
    echo setting pipeline for "$PIPELINE_NAME"
    fly -t $TARGET set-pipeline -p "$PIPELINE_NAME" \
        -c "pipelines/$1.yml" \
        -l ./shared-secrets.yml \
        -l ./github-key.yml \
        -l ./datadog-api-key.yml \
        -l ~/workspace/log-cache-ci/scripts.yml

    rm shared-secrets.yml github-key.yml datadog-api-key.yml
}

function sync_fly {
    fly -t $TARGET sync
}

function set_pipelines {
    if [ "$pipeline" = all ]; then
        for pipeline_file in $(ls "pipelines/"); do
            set_pipeline "${pipeline_file%.yml}"
        done
        exit 0
    fi

    set_pipeline "$pipeline"
}

function print_usage {
    echo "usage: $0 <pipeline | all>"
}

function main {
    set_globals $1
    validate
    sync_fly
    set_pipelines
}
main $1 $2
