---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor-docker-virtual.usw1.packages.broadcom.com/relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.26.0
    username: ((metric-store.jfrog-svc-username))
    password: ((metric-store.jfrog-svc-password))

inputs:
  - name: metric-store-ci
  - name: certs

outputs:
  - name: archived-certs

run:
  path: metric-store-ci/tasks/generate-certs/archive-certs
