---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.26.0

inputs:
  - name: metric-store-ci
  - name: certs

outputs:
  - name: archived-certs

run:
  path: metric-store-ci/tasks/generate-certs/archive-certs
