---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor-docker-virtual.usw1.packages.broadcom.com/certbot/dns-google
    tag: latest
    username: ((metric-store.jfrog-svc-username))
    password: ((metric-store.jfrog-svc-password))

inputs:
  - name: gcp-service-account
  - name: metric-store-ci

outputs:
  - name: certs

params:
  CERT_DOMAINS:
  CERT_EMAIL:

run:
  path: metric-store-ci/tasks/generate-certs/generate-certs
