---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk

inputs:
  - name: metric-store-ci
  - name: gcp-service-account
  - name: extracted-certs

params:
  PROJECT_NAME:
  ENV_NAME:

run:
  path: metric-store-ci/tasks/generate-certs/install-certs
