---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.26.0

params:
  GCP_SERVICE_ACCOUNT_JSON:

inputs:
  - name: metric-store-ci

outputs:
  - name: gcp-service-account

run:
  path: metric-store-ci/tasks/generate-certs/prepare-service-account
