#!/bin/bash
set -exu

source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars

if [ "$KEEP_ALIVE" = true ]; then
  bosh -d $DEPLOYMENT_NAME run-errand $ERRAND --keep-alive
else
  bosh -d $DEPLOYMENT_NAME run-errand $ERRAND
fi
