#!/bin/bash
set -exu

source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars

errand="bosh -d $DEPLOYMENT_NAME run-errand $ERRAND"

if [ -z $INSTANCE ]; then
  errand="$errand --instance=$INSTANCE"
fi

if [ "$KEEP_ALIVE" = true ]; then
  errand="$errand --keep-alive"
fi

$(echo $errand)
