#!/bin/bash
set -exu

pushd bbl-state/$BBL_STATE_DIR
  eval $(bbl print-env)
  export BOSH_CA_CERT=$(bbl director-ca-cert)
popd


if [ "$KEEP_ALIVE" = true ]; then
  bosh -d $DEPLOYMENT_NAME run-errand $ERRAND --keep-alive
else
  bosh -d $DEPLOYMENT_NAME run-errand $ERRAND
fi
