#!/bin/bash

set -exu

. ./metric-store-ci/tasks/shared_bash

calculate_version bosh-dev-release-dir/src/internal/version/version.go bosh-dev-release-version bosh-new-dev-release-version ${RELEASE_KEYWORD}
dev_version=$(cat bosh-new-dev-release-version/version | sed -r 's/-/+/')

pushd bosh-dev-release-dir
  configure-blobstore

  if [ $DEPLOY_REPO_VERSION_BUMP = true ]; then
    write_version ${dev_version} src/internal/version
  fi

  git rev-parse HEAD > sha
  cat sha

  # put go source files in src directory so go build is pleased.
  mkdir -p src/github.com/cloudfoundry/metric-store-release/src/{pkg,internal,cmd}
  cp -r vendor/* src/

  cp -r src/pkg src/github.com/cloudfoundry/metric-store-release/src
  cp -r src/internal src/github.com/cloudfoundry/metric-store-release/src
  cp -r src/cmd src/github.com/cloudfoundry/metric-store-release/src

  bosh create-release --force \
    --tarball ../metric-store-dev-release/release-${dev_version}.tgz \
    --version "${dev_version}"
popd
