#!/bin/bash

set -exu

. ./log-cache-ci/tasks/shared_bash

calculate_version bosh-dev-release-dir/src/version bosh-dev-release-version bosh-new-dev-release-version "dev"
dev_version=$(cat bosh-new-dev-release-version/version)

pushd bosh-dev-release-dir
  if [[ -n ${JSON_KEY:-} ]]; then
    cat << EOF > config/private.yml
---
blobstore:
  options:
    credentials_source: static
    json_key: |
      $(echo ${JSON_KEY})
EOF
  fi

  bosh create-release --force \
    --tarball ../metric-store-dev-release/release-${dev_version}.tgz \
    --version "${dev_version}"
popd
