---
platform: linux

inputs:
- name: metric-store-ci
- name: bosh-dev-release-dir
- name: bosh-dev-release-version
- name: golang-release

outputs:
- name: metric-store-dev-release
- name: bosh-new-dev-release-version

run:
  path: metric-store-ci/tasks/create-dev-release/task

params:
  JSON_KEY:
  OSS_RELEASE: false
  # A keyword to be added to the release version to identify branch builds
  RELEASE_KEYWORD: dev
