platform: linux

inputs:
- name: metric-store-ci # - This repo
- name: release-repo   # - The parent bosh release repository
- name: source-repo    # - The submodule to bump

outputs:
- name: bumped-release-repo # - The updated release-repo with the bumped submodule.

run:
  path: metric-store-ci/tasks/bump-submodule/task

params:
  # - Required
  # - The path of the source repository to bump.
  # - This path is relative to the release repository.
  SUBMODULE_PATH:

