#!/bin/bash

set -ex

mkdir -p $HOME/.ssh
ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

pushd source-repo
  target_sha="$(git rev-parse HEAD)"
  source_repo_dir=${PWD}
popd

pushd "release-repo/$SUBMODULE_PATH"
  git fetch ${source_repo_dir}
  git checkout "$target_sha"
popd

cp -r release-repo/. bumped-release-repo/
