#!/bin/bash

. ./log-cache-ci/tasks/shared_bash

set -ex

export GOPATH="$PWD/go"

set +x
if ! [[ -z "${GITHUB_PRIVATE_KEY}" ]]; then
  setup_github_ssh ${GITHUB_PRIVATE_KEY}
fi
set -x

if [[ -z "${SUB_FOLDERS}" ]]; then
  pushd source-repo
    go mod download
    go test ./... -race
  popd
else
  for sub in ${SUB_FOLDERS}; do
    pushd source-repo/${sub}
      go mod download
      go test ./... -race
    popd
  done
fi
