#!/bin/bash

set -exu

if [[ -n ${BBL_STATE_DIR:-} ]]; then
  pushd "bbl-state/$BBL_STATE_DIR"
    eval "$(bbl print-env)"
  popd
fi

: ${BOSH_ENVIRONMENT:?must provide BOSH_* environment variables or BBL_STATE_DIR}

bosh releases | grep "${RELEASE_NAME}" | grep -v "*" > releases
while read release_line; do
  release_name=$(echo ${release_line} | cut -d' ' -f1)
  release_version=$(echo ${release_line} | cut -d' ' -f2)

  bosh delete-release -n ${release_name}/${release_version}
done <release
