#!/bin/bash

set -exu

. ./metric-store-ci/tasks/shared_bash

git config --global user.email "cf-log-cache+github@pivotal.io" && git config --global user.name "Metric Store CI"
set +x
if ! [[ -z "${GITHUB_PRIVATE_KEY}" ]]; then
  setup_github_ssh "${GITHUB_PRIVATE_KEY}"
fi
set -x

git clone p-metric-store-release bumped-p-metric-store-release

pushd oss-metric-store
  oss_metric_store_sha=$(git rev-parse HEAD)
popd

pushd bumped-p-metric-store-release
  unset GOPATH

  go get github.com/cloudfoundry/metric-store-release@${oss_metric_store_sha}
  go mod tidy
  go mod vendor

  git add go.mod go.sum vendor
  if [ $(git diff --staged | wc -l) -eq 0 ]; then
    echo "Nothing to commit!"
  else
    git commit -m "Bump OSS Metric Store"
  fi
popd
