#!/bin/bash -euf
echo "running build and install"
export RELEASE_VERSION=$(cat tile-version/version | sed s/-dev// | sed s/-build// )

mkdir -p releases
set +f
mv metric-store-dev-release/*.tgz releases
set -f

RELEASE_URLS=(
  https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release
  https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release
)

pushd releases
    for URL in ${RELEASE_URLS[@]}; do
        curl \
          --location \
          --remote-name \
          --remote-header-name \
          --silent \
          --retry 5 \
          ${URL} || true
    done
popd

mkdir -p baked-tile
TILE_FILE=baked-tile/${TILE_NAME}-${RELEASE_VERSION}.pivotal

kiln bake \
    --version "$RELEASE_VERSION" \
    --metadata metric-store-release/tile/metadata.yml \
    --icon metric-store-release/tile/icon.png \
    --releases-directory releases \
    --jobs-directory metric-store-release/tile/jobs \
    --instance-groups-directory metric-store-release/tile/instance_groups \
    --bosh-variables-directory metric-store-release/tile/variables \
    --output-file ${TILE_FILE}

echo "Freshly baked tile 🍞: ${TILE_FILE}"

source environment/environment.sh
source deployment-tools/prelude.sh
source deployment-tools/omg.sh

stemcell_filename=$(download-product ${STEMCELL_URL})

omg upload-product --product ${TILE_FILE}
omg stage-product --product-name "observability-store" --product-version ${RELEASE_VERSION}
omg configure-product --config log-cache-ci/tile/metric-store-config.yml
omg upload-stemcell --stemcell ${stemcell_filename} --floating true --shasum ${STEMCELL_SHA}
omg apply-changes --product-name "observability-store"
