#!/bin/bash
set -ex

if [ -z "$BASE_PACKAGE" ]; then
  echo BASE_PACKAGE was not set
  exit 1
fi

if [ -z "$CONTEXT_PATH" ]; then
  echo CONTEXT_PATH was not set
  exit 1
fi

# record ci root for later use
ciroot="$PWD"

pushd source-repo
  git submodule update --init --recursive
  export GOPATH="$PWD"
popd

source_base_package=${GOPATH}/src/${BASE_PACKAGE}

# compute sha for tagging the docker image
sha="$(cd ${source_base_package} && git rev-parse @)"

# copy over build context and tag
pushd "context-repo/$CONTEXT_PATH" > /dev/null
  mkdir -p "$ciroot/build-image/build"
  cp -r "${GOPATH}/." "$ciroot/build-image/build/"
  cp Dockerfile "$ciroot/build-image/build/"
  echo "$sha" > "$ciroot/build-image/tag"
popd > /dev/null
