#!/bin/bash
set -eux

workspace=$(pwd)

bumper_path=$GOPATH/src/github.com/loggregator/bumper
mkdir -p $bumper_path
cp -R bumper-tool/. $bumper_path
pushd $bumper_path/cmd/bumper
    go build -o $workspace/bumper/bumper
popd

pushd dest
    DEST_COMMIT=$(git rev-parse HEAD)
popd

bump_sha=""
pushd source
    $workspace/bumper/bumper --commit-range ${DEST_COMMIT}..HEAD --verbose
    bump_sha=$($workspace/bumper/bumper --commit-range ${DEST_COMMIT}..HEAD)
popd

if [ -z $bump_sha ]; then
    echo "There are no commits to bump!"
    cp -R dest/. merged-dest

    exit 0
fi

cp -R dest/. merged-dest

pushd merged-dest
    git remote add source ../source
    git fetch source ${SOURCE_BRANCH}
    git merge $bump_sha --ff-only
popd
